# Site settings
site: Ephesus
title: Ephesus - Minimalist Jekyll Theme
keywords: ephesus, blog
description: >-
  Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  Europe/Istanbul
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Gabriel Dornelles
  bio: Computer Vision Engineer
  picture: assets/images/profile.jpg 
  github: GabrielDornelles # github username
  twitter: gabdrnelles # twitter username
  instagram: gabriel_drnelles # instagram username
  youtube: https://www.youtube.com/channel/UC_dKBMIDx1foQ6gkNJ7YJ4A # youtube username
  linkedin: gabriel-dornelles-m # linkedin username
  email: gabrieldornellesmonteiro@hotmail.com # email adress


# URL settings
url: "https://gabrieldornelles.github.io/" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
